### ISSUE TITLE
Error al crear token

### ISSUE THREAD

**Issue by Cicko** [ULL-ESIT-GRADOII-TFG/ghshell#5]
![image](https://user-images.githubusercontent.com/16807198/27845094-54488d40-6123-11e7-83d5-ca805ddb03bd.png)

Me salta este error al iniciar el programa e insertar las credenciales de github. Viendo la línea 241 del fichero index.js vemos que sale esto: 
![image](https://user-images.githubusercontent.com/16807198/27845119-ae62a608-6123-11e7-85c4-eb48ef605076.png)

Por lo tanto el error se debe al ejecutar la función .then().

Intente borrar ese .then() desde la carpeta /usr/lib/node_modules/ghshell/index.js donde se encuentra el fichero y ahora me funciona, al parecer, bien:

![image](https://user-images.githubusercontent.com/16807198/27845147-15451702-6124-11e7-8078-b6a4f1fd524b.png)

Espero que te haya ayudado con algo. Saludos, Rudy

**Comment by jjlabrador** [comment]
Hola, Rudy!

Muchas gracias por reportar el error. Ese error y otros cambios menores los tenía corregidos en otra rama y no había hecho el merge correspondiente. Ya he actualizado la rama ```master``` (commit 4908609) y publicado la nueva versión del paquete NPM (v1.0.1).

Con esta nueva versión no deberías tener problemas. Si detectas otro error, no dudes en reportarlo.

Gracias nuevamente.

Saludos!
